[tox]
minversion = 3.12.0
envlist = py312, py313, semgrep, update-readme, flake8, isort, black, mypy
isolated_build = true
skipsdist = true
changedir = {toxinidir}

[gh-actions]
python =
    3.12: py312, semgrep, flake8, isort, black, mypy

[testenv:py312]
usedevelop=True
allowlist_externals = poetry
deps =
    poetry
    pytest
    pytest-cov
commands =
    poetry install --no-root
    pytest --basetemp={envtmpdir} -vv -s --cov=src -k "test_" --cov-report html:{toxinidir}/.tox/report/ --cov-report xml:{toxinidir}/.tox/report/coverage.xml
setenv =
    PYTHONPATH = {toxinidir}/src

[testenv:flake8]
basepython = python3.12
deps = poetry
commands =
    poetry run flake8 {toxinidir}/src

[testenv:semgrep]
deps =
    semgrep
commands =
    semgrep --config=p/security-audit \
            --config=p/secrets \
            --config=p/python \
            --config=p/ci \
            --config=p/default \
            --config=p/comment \
            --config=p/cwe-top-25 \
            --config=p/owasp-top-ten \
            --config=p/secure-defaults \
            --config=p/docker-compose \
            --config=p/dockerfile \
            --config=p/bandit \
            --metrics=off \
            --dryrun

[testenv:mypy]
basepython = python3.12
deps = poetry
commands =
    poetry run mypy --cache-dir={toxinidir}/.tox/.mypy_cache --non-interactive --install-types --no-namespace-packages {toxinidir}/src

[testenv:isort]
basepython = python3.12
deps = poetry
commands =
    poetry run isort --check-only --diff --line-length 79 {toxinidir}/src

[testenv:black]
basepython = python3.12
deps = poetry
commands =
    poetry run black --line-length 79 --check {toxinidir}/src

[testenv:update-readme]
usedevelop = True
deps =
    toml
commands =
    python update_readme.py
