name: "\U0001F680 Feature Request"
description: Request a feature and help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reaching out.

        We track new features for the product

        Please fill in the fields below with the information
  - type: input
    attributes:
      label: Your full name
      description: |
        Enter your full name so we can identify you!
      validations:
        required: true
  - type: input
    attributes:
      label: client:<clientName> | internal
      description: |
        Is the feature an internal request or made by a client?
      validations:
        required: true
  - type: textarea
    attributes:
      label: What solution would you like?
      description: Describe the solution and what you expect from it
  - type: textarea
    attributes:
      label: What other alternatives did you consider?
      description: Describe other alternative solutions and features you thought of.
  - type: textarea
    attributes:
      label: References, screenshots, or design?
      description: Attach any content that helps us visualize the feature.